PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures
    problem_on_unmodified_line: ignore
    command: ['bundle', 'exec', 'rubocop']
  BundleCheck:
    enabled: true
